export enum TireType {
  SCOOTER = "SCOOTER",
  ONROAD_AUTOMATIC = "ONROAD_AUTOMATIC",
  ONROAD_SPORT = "ONROAD_SPORT",
  RACING = "RACING",
  ON_OFF_ROAD = "ON_OFF_ROAD",
  OFF_ROAD = "OFF_ROAD",
  CLASSIC = "CLASSIC",
}
